import { chromium } from '@playwright/test';
const b = await chromium.launch({ args: ['--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 800 }, deviceScaleFactor: 2, reducedMotion: 'no-preference' });
const errs = [];
p.on('pageerror', (e) => errs.push('PAGEERROR ' + e.message));
p.on('console', (m) => m.type() === 'error' && errs.push('CONSOLE ' + m.text().slice(0,200)));
await p.goto('http://localhost:5183/', { waitUntil: 'load' });
await p.waitForTimeout(Number(process.env.WAIT ?? 3000));
await p.screenshot({ path: process.env.OUT ?? '/tmp/cl.png' });
console.log(errs.length ? errs.slice(0,6).join('\n') : 'clean, no console errors');
await b.close(); process.exit(0);
